#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jun  8 17:14:10 2020

@author: thanhng
"""
first_dict = {'dover': 'dover silicone urine meter',
             'BD PosiFlush': 'BD PosiFlush SF Saline Flush Syringe',
             'BD BBLTM Gram': 'BD BBLTM Gram',
             'Ivoclar Vivadent': 'Ivoclar Vivadent IPS',
             'HEMASHIELD PLATINUM':'HEMASHIELD PLATINUM Woven Double Velour Vascular Graft',
             'ARCHITECT': 'ARCHITECT C Peptide',
             'Oncomine Dx Target Test RNA Control': 'Oncomine Dx Target Test RNA Control',
             'Stretch VL Ureteral Stent Set': 'Stretch VL Ureteral Stent Set',
             'BIOMET StageOne': 'BIOMET StageOne',
             'RayStation/RayPlan B': 'RayStation/RayPlan B',
             'IMMULITE  Systems E Estradiol': 'IMMULITE  Systems E Estradiol',
             'CareFusion Alaris': 'CareFusion Alaris Pump',
              'AAMI  NONREINF SURGICAL': 'AAMI  NONREINF SURGICAL',
             'CERTAIN BELLATEK ENCODE HEALING': 'CERTAIN BELLATEK ENCODE HEALING ABUTMENT',
             'SIGNA': 'SIGNA Nuclear Magnetic Resonance Imaging System',
             'CombiDiagnost':'CombiDiagnost',
             'Polysorb Braided Absorbable Suture': 'Polysorb Braided Absorbable Suture',
             'VitreQ G':'VitreQ G Injection Needle',
             'HUDSON RCI COMFORT FLO': 'HUDSON RCI COMFORT FLO',
             'Philips Healthcare Ingenuity Core': 'Philips Healthcare Ingenuity Core',
             'Siemens Cios': 'Siemens Cios X-Ray system',
             'Abbott Accelerator': 'Abbott Accelerator a3600',
             'Gentell Honey Hydrogel': 'Gentell Honey Hydrogel',
             'Sensor Nitinol Wire with Hydrophilic Tip': 'Sensor Nitinol Wire',
             'Acutus Medical AcQGuide Flex': 'Acutus Medical AcQGuide Flex',
             'Acutus': 'Acutus Medical AcQGuide Flex',
             'Butterfly iQ Ultrasound System': 'Butterfly iQ Ultrasound System',
             'Atellica CH': 'Atellica CH',
             'STEALTH SPRING CLIP': 'STEALTH SPRING CLIP',
             'GORE EXCLUDER': 'GORE EXCLUDER Endoprosthesis',
             'BriteBlade Pro': 'BriteBlade Pro Single-Use Fiber Optic Mac',
             'MicroVention Terumo': 'MicroVention Terumo',
             'MICRO-PSD':'MICRO-PSD EXTERNAL BEAM PHOTON',
             'Arrow Berman Angiographic Catheter': 'Arrow Berman Angiographic Catheter',
             'Hudson RCI Sheridan': 'Hudson RCI Sheridan',
             'da Vinci': 'da Vinci SP Surgical System',
             'Endotrac ECTR': 'Endotrac ECTR Blade',
             'COLUMBUS':'COLUMBUS PLAT PLASMAPORE',
             'AAMI': 'AAMI SURGICAL GOWN',
             'Prometra': 'Prometra Programmable',
             'LIFEPAK': 'LIFEPAK Defibrillator',
             'ACUSON':'ACUSON Diagnostic Ultrasound System',
             'MEDTRONIC CARELINK': 'MEDTRONIC CARELINK',
             'PageWriter':'PageWriter Government Bundle',
             'Alinity':'Alinity Vitamin D Reagent Kit',
             'alinity': 'Alinity Vitamin D Reagent Kit',
             'Cyberonics VNS': 'Cyberonics VNS',
             'vns therapy': 'vns therapy',
             'CIVCO': 'CIVCO Needle',
             'SonoSite':'SonoSite Needle',
             'VITROS': 'VITROS Reagent',
             'Zimmer': 'Zimmer Guide Wire',
             'NxStage PureFlow': 'NxStage PureFlow',
             'Bi Patient Monitor': 'B40i Patient Monitor',
             'Solar':'Solar Patient Monitoring System',
             'Biomet Microfixation':'Biomet Microfixation RapidFlap',
             'CHS Custom Convenience':'CHS Custom Convenience',
             'Bronchofiberscope':'Bronchofiberscope',
             'CAPNOSTREAM': 'CAPNOSTREAM PRINTER',
             'Stryker Mako Vizadisc': 'Stryker Mako Vizadisc Procedure Tracking Kit',
             'Gentle Thread': 'Gentle Thread Interference Screw',
             'INTEGRIS': 'INTEGRIS IMAGING APPLICATION',
             'philips suresigns': 'philips suresigns monitor',
             'suresigns': 'philips suresigns monitor',
             'Duo-Flow': 'Duo-Flow Hemodialysis catheter insertion kits',
             'SOFT-LINE': 'SOFT-LINE DUO-FLOW DOUBLE LUMEN CATHETER TRAY',
             'DORO LUCENT': 'DORO LUCENT Transitional Member',
             'DigitalDiagnost':'DigitalDiagnost Detector (Stitching Patient Support)',
             'Aplicare Povidone Iodine Prep Pads': 'Aplicare Povidone Iodine Prep Pads',
             'Temperature Sensor Catheter': 'Temperature Sensor Catheter',
             'JOURNEY BCS': 'JOURNEY BCS Knee Conventional Polyethylene Inserts',
             'PDS': 'PDS Needle',
             'Vectri': 'Vectri Trial Screening Lead Kit for Spinal Cord Stimulation',
             'Endo': 'Endo Articulating Vascular',
             'PROLENE':'PROLENE SUTURE MONO BLUE',
             'OmniDiagnost': 'OmniDiagnost Angiographic and Diagnostic',
             'Prismaflex': 'Prismaflex',
             'CyberKnife': 'CyberKnife Robotic Radiosurgery System',
             'GE LOGIQ': 'GE LOGIQ ultrasound system',
             'Philips HeartStart': 'Philips HeartStart',
             'ST-AIA PACK': 'ST-AIA PACK',
             'IMMULITE': 'IMMULITE',
             'HYPOTHERMIA': 'HYPOTHERMIA Elasto-Gel',
             'ADVIA Centaur': 'ADVIA Centaur',
             'SOMATOM': 'SOMATOM Definition Flash Computed tomography x-ray diagnostic system',
             'radial': 'radial stem Orthopedic implant',
             'Medtronic MiniMe': 'medtronic minimed infusion pump',
             'medtronic entrust': 'medtronic entrust escudo',
              'medtronic synchromed': 'medtronic synchromed implantable drug infusion',
             'electric wheelchairs': 'electric wheelchairs bases',
             'electric wheelchair': 'electric wheelchair bases',
             'Percuvance': 'Percuvance Scissors Tool Tip',
             'MyCareLink': 'MyCareLink Patient Monitors',
             'Beijing Syntech Laser': 'Beijing Syntech Laser',
             'Safety Deluxe': 'Safety Deluxe Bone Marrow',
             'DLP': 'DLP Adapter',
             'STAT': 'STAT Gravity Flow Controller',
             'Tissu-Trans': 'Tissu-Trans Filtron',
             'LEGIO': 'LEGIO CONE IMPACTOR HEADS',
             'Coulter': 'Coulter PrepPlus',
             'Maquet': 'Maquet Dry Seal Suction',
             'Atrium': 'Atrium Medical Oasis Blood Recovery Drains',
             'Siemens': 'Siemens RAPIDLab Blood Gas Analyzer',
             'AnastoCiip': 'AnastoClip Universal Clip Remover',
             'anastoclip': 'AnastoClip Universal Clip Remover',
             'Merge': 'Merge Eye Station Healthcare',
             'iConnect Access': 'iConnect Access',
             'MicroVue': 'MicroVue SC5b-9',
             'Philips Healthcare': 'philips brilliance',
             'philips brilliance':'philips brilliance',
             'brilliance': 'philips brilliance',
             'philips azurion': 'philips azurion',
             'philips volcano': 'philips volcano vascular system',
             'philips intellivue': 'philips intellivue',
             'karl storz': 'karl storz fiberscope',
             'randox liquid': 'randox liquid cardiac controls',
             'randox calcium colorimetric method': 'randox calcium colorimetric method',
             'randox laboratories': 'randox liquid cardiac controls',
             'abl flex': 'abl flex',
             'ABL analyzer': 'ABL analyzer',
             'Abutment Screw': 'Abutment Screw Retrieval Instrument',
             'ACCOLADE': 'ACCOLADE Pacemaker',
             'accu chek': 'accu chek blood glucose monitoring system',
             'accu chek aviva': 'accu chek blood glucose monitoring system',
             'Achieva': 'Achieva Conversion',
             'ADVIA': 'ADVIA Chemistry',
             'ACUVUE': 'ACUVUE OASYS contact lenses',
             'aap': 'aap Implante' ,
             'Abbott ARCHITECT': 'Abbott ARCHITECT',
             'ACNow': 'ACNow Systems',
             'AF':'Arrow AutoFuser Disposable Pain Control Pump',
             'Affixus': 'Affixus Hip Fracture',
             'agb pressure': 'agb pressure injectable',
             'AIA': 'AIA Analyzer',
             'Alaris': 'Alaris Pump',
             'AD-TECH': 'AD-TECH Spencer',
             'Aguja': 'Aguja de Aspiracion',
             'Allura': 'Allura Vascular,cardiovascular and neurovascular imaging applications',
             'Alcon': 'Alcon or Endure Ophthalmic Microscope',
             'Apollo': 'Apollo x-ray equipment',
             'APLIO': 'APLIO diagnostic ultrasound system',
             'ALTRUA': 'ALTRUA pacemaker',
             'APTIO': 'APTIO RACK MODULE',
             'AngioJet': 'AngioJet Ultra Consoles Thrombectomy System',
             'Aquarius': 'Aquarius Deletion Probe',
             'achilles': 'achilles bone sonometer',
             'agfa': 'agfa digital radiography',
             'aisys': 'aisys anesthesia system',
             'aries': 'aries assay',
             'amnisure': 'amnisure rom test',
             'arrow': 'arrow picc kit',
             'Apolipoprotein': 'apolipoprotein',
             'artis': 'artis biplane',
             'atellica': 'atellica humidity pack',
             'babi plus': 'babi plus pressure relief manifold',
             'axiom artis': 'axiom artis',
             'bd microtainer': 'bd microtainer tube',
             'bd microtainertubes':'bd microtainer tube',
             'bronchovideoscope': 'bronchovideoscope',
             'anastociip': 'anastociip clip remover',
             'angiodynamics': 'angiodynamics venacure nevertouch',
             'bd vacutainer': 'bd vacutainer blood collection tubes',
             'arrowg': 'arrowg ard blue advance jacc',
             'cordis': 'cordis catheters',
             'canon aquilion': 'canon aquilion',
             'bvi beaver': 'bvi beaver safety knife',
             'carescape': 'carescape respiratory',
             'centricity': 'centricity pacs',
             'centurion': 'centurion surgical trays',
             'cobas': 'cobas analyzer',
             'afxml': 'Arrow AutoFuser Disposable Pain Control Pump',
             'dimension': 'dimension vista cartridge',
             'auriga': 'auriga lazer system',
             'essentio': 'essentio pacemaker',
             'olympus': 'olympus pleuravideoscope',
             'medipress': 'medipress pneumatic compression system',
             'zyno': 'zyno medical administration set',
             'berchtold':'berchtold chromophare surgical light',
             'cad':'cad yellow medication cassette reservoir',
             'covidien emprint':'covidien emprint percutaneous antenna',
             'cobalt': 'cobalt bone cement',
             'epidural catheterization': 'epidural catheterization',
             'equistream':'equistream hemodialysis catheter',
             'km': 'ALEUTIAN Interbody Spacer Systems',
             'aiiuraxperfdlo': 'aiiura xper',
             'aiiura xper f dr table': 'aiiura xper',
             'bard': 'bard catheter',
             'arctic': 'arctic sun temperature management system',
             'arjohuntleigh': 'arjohuntleigh pump',
             'bodyguard': 'bodyguard infusion pump tubing',
             'boss instruments': 'boss instruments obstetric forceps',
             'assurity': 'assurity pulse generator',
             'atar': 'atar disposable extension cable',
             'autocomp': 'autocomp6 high speed compounder',
             'cardiosave': 'cardiosave intra aortic balloon pump',
             'cc': 'cc resistance syringe',
             'cascade': 'cascade abrazo',
             'discovery': 'discovery nuclear magnetic resonance imaging system',
             'biomet': 'biomet stageone hip femoral reinforcement',
             'giraffe': 'giraffe omnibed carestation',
             'heartstart': 'Philips HeartStart',
             'comprehensive':'comprehensive humeral tray',
             'conmed anchor': 'conmed anchor tissue retrieval system',
             'cm': 'guidewire',
             'vitek': 'vitek identification card',
             'fresenius gallon': 'fresenius gallon dry acid dissolution unit',
             'brand name':'Dexcom G6',
             'pacific medical': 'pacific medical ge corometrics nautilus ultrasound',
             'endotrac': 'endotrac triangle blade',
             'frontal': 'frontal apron closure',
             'egia': 'egia articulating thick sulu',
             'enflow': 'enflow cartridge',
             'filmarray': 'filmarray gastrointestinal panel',
             'exactamix': 'exactamix eva bags',
             'duo flow': 'duo flow hemodialysis catheter',
             'immunoglobulin': 'immunoglobulin vitro diagnostic assay',
             'elite': 'elite hv introducer',
             'fresenius': 'fresenius hemodialysis system',
             'frontal quick drop or apron': 'frontal apron closure',
             'cetkn accu bloc perifix kit nrfit': 'accu bloc perifix kit',
             'cehkn accu bloc perifix kit nrfit': 'accu bloc perifix kit',
             'cetkfcn': 'accu bloc perifix kit',
             'cetkfcsn': 'accu bloc perifix kit',
             'cetkn': 'accu bloc perifix kit',
             'apexpro telemetry': 'apexpro telemetry system',
             'bardport': 'bardport titanium implantable port',
             'bd facslyri': 'bd facslyric flow cytometer',
             'bioflo': 'bioflo single plastic',
             'biograph': 'biograph mct',
             'biomerieux': 'biomerieux vidas system',
             'ellipse': 'ellipse defibrillator',
             'drill tapered': 'drill tapered',
             'gibson healthcare': 'gibson healthcare membrane extended',
             'ingenuity': 'ingenuity computed tomography xray system',
             'brightview': 'brightview',
             'cepheid': 'cepheid respiratory control panel',
             'certai': 'certai bellatek',
             'certair': 'certai bellatek',
             'custom': 'custom healthcare systems dialysis kit',
             'carestation': 'carestation anesthesia systems',
             'cell': 'cell marque',
             'arthrex': 'arthrex anchor',
             'automate': 'automate aliquot module',
             'cardinal health jackson': 'cardinal health jackson pratt channel',
             'leadcare': 'leadcare blood lead analyzer',
             'leica surgical': 'leica surgical microscope',
             'dense bone drill': 'dense bone drill',
             'corflo percutaneous endoscopic gastrostomy': 'corflo percutaneous endoscopic gastrostomy',
             'ge healthcare millennium': 'ge healthcare millennium',
             'ge vivid': 'ge vivid ultrasound system',
             'ge healthcare': 'ge healthcare prodigy',
             'getinge': 'getinge washer disinfectors',
             'deroya': 'deroyal feeding tube',
             'deroyal enteral safe feeding tubes': 'deroyal feeding tube',
             'deroya dolphin inflation device': 'deroyal dolphin inflation device',
             'powerport clearvue isp': 'powerport clearvue',
             'powerport': 'powerport implantable port',
             'heartware': 'heartware medtronic ventricular assist system',
             'icu medical': 'icumedical chemolock',
             'icumedical': 'icumedical chemolock' ,
             'edwards lifesciences intraclude': 'edwards lifesciences intraclude intra aortic occlusion device',
             'edwards sapien ultra transcatheter': 'edwards sapien ultra transcatheter heart valve system',
             'natrelle': 'natrelle silicone breast implants',
             'neuviz': 'neuviz multi slice ct scanner',
             'paltop dynamic dental implant': 'paltop dynamic dental implant',
             'paltop': 'paltop surgical kit',
             'panda': 'panda warmer infant radiant',
             'platinium': 'platinium cardioverter defibrillator',
             'implant': 'implant retrieval instrument',
             'system axiom': 'system axiom',
             'monoject': 'monoject hypodermic safety needle',
             'royalsilk': 'royalsilk',
             'gore': 'gore endoprosthesis',
             'merlin pcs': 'merlin pcs programmer',
             'micro surgery handpiece': 'micro surgery handpiece sgs',
             'monaco': 'monaco radiation treatment',
             'monoject': 'monoject needle',
             'mosaiq': 'mosaiq oncology information system',
             'multidiagnost eleva': 'multidiagnost eleva',
             'rosa': 'rosa brain',
             'teleflex': 'teleflex medical hudson neptune heated humidifier',
             'temperature': 'temperature sensing catheter',
             'tlc': 'tlc therapeutic medical laser system'
             }


second_dict = {
            'accu chek': 'accu chek blood glucose monitoring system',
            'agb pressure': 'agb pressure injectable',
            'heartware': 'heartware medtronic ventricular assist system',
            'medtronic minimed': 'medtronic minimed infusion pump',
            'minimed model': 'medtronic minimed infusion pump',
            'minimed infusion pump': 'medtronic minimed infusion pump' ,
            'minimed g insulin infusion pump':'medtronic minimed infusion pump',
            'minimed insulin pump': 'medtronic minimed infusion pump',
            'gripper needles sold as part of port a cath ii single lumen system': 'gripper needles',
            'gentell hydrogel ag oz tube': 'gentell honey hydrogel',
            'guide wire mm x in': 'zimmer guide wire ball tip',
            'smooth guide wire bullet tip': 'zimmer guide wire ball tip',
            'zms intramedullary fixation smooth guide wire': 'zimmer guide wire ball tip',
            'm dn intramedullary fixation humeral guide wire': 'zimmer guide wire ball tip',
            'ball tip guide wire mmxcm': 'zimmer guide wire ball tip',
            'mm ball nose guide wire': 'zimmer guide wire ball tip',
            'pressure sentinel intramedullary reaming system guide wire bullet tip mm diameter':'zimmer guide wire ball tip',
            'zms intramedullary fixation smooth guide wire': 'zimmer guide wire ball tip',
            'guide wire ball tip': 'zimmer guide wire ball tip',
            'zimmer guide wire': 'zimmer guide wire ball tip',
            'guide wire': 'zimmer guide wire ball tip',
            'fujifilm fdr go plus mobile x ray system': 'fujifilm fdr go plus',
            'digitaldiagnost detector stitching patient support': 'digital diagnost',
            'lamicel pk':'lamicel pk cervical dilator',
            'dexcom': 'dexcom g6',
            'sterile co flex': 'sterile co flex',
            'synchron systems':  'synchron systems reagent',
            'syngo':  'syngo cardiac',
            'synthes': 'synthes',
            'sysmex': 'sysmex',
            'terumo azur':  'terumo azur peripheral coil system',
            'terumo capiox': 'terumo capiox nx oxygenator',
            'thermacare heatwraps': 'thermacare heatwraps joint pain therapy',
            'thio med': 'thio med' ,
            'tri staple':  'tri staple curved tip intelligent reload',
            'trimed hex': 'trimed hex cortical screw',
            'truliant tibial': 'truliant tibial trial handle' ,
            'uniq': 'uniq',
            'universal':  'universal sexual health testing kit',
            'urodiagnost': 'urodiagnost eleva',
            'vista dental':  'vista dental products',
            'visualase':  'visualase cooled laser applicator system',
            'vitality spinal fixation system':  'vitality spinal fixation system spinal interlaminal',
            'viva': 'viva e'
                    }
